name: Types

on:
  push:
    branches: [main, openpgpjs_v5]
  pull_request:
    branches: [main, openpgpjs_v5]

jobs:
  lint:
    name: Test type definitions

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '15'
    - run: npm ci
    - run: npm run test-type-definitions
